# Generated by Django 5.1.1 on 2025-04-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('s', models.CharField(max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar/no-avatar.png', upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Пол')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False, verbose_name='Одобрение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('awaiting_payment', 'Ожидание оплаты'), ('awaiting_order', 'Ожидание ордера'), ('order', 'Ордер получен')], default='pending', max_length=20, verbose_name='Статус')),
                ('dormitory_cost', models.PositiveIntegerField(verbose_name='Выбранная стоимость проживания')),
                ('test_answers', models.JSONField(default=dict, verbose_name='Ответы теста')),
                ('test_result', models.CharField(blank=True, max_length=1, null=True, verbose_name='Результат теста')),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='Скрин оплаты')),
                ('is_full_payment', models.BooleanField(blank=True, null=True, verbose_name='Полная оплата')),
                ('ent_result', models.PositiveIntegerField(blank=True, null=True, verbose_name='Результат ЕНТ')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_places', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('rooms_for_two', models.PositiveIntegerField(verbose_name='Количество комнат на 2')),
                ('rooms_for_three', models.PositiveIntegerField(verbose_name='Количество комнат на 3')),
                ('rooms_for_four', models.PositiveIntegerField(verbose_name='Количество комнат на 4')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('priority', models.IntegerField(default=0, help_text='Чем больше число, тем выше приоритет', verbose_name='Приоритет')),
                ('data_type', models.CharField(choices=[('file', 'Файл'), ('numeric', 'Числовое значение')], max_length=20, verbose_name='Тип данных')),
                ('auto_fill_field', models.CharField(blank=True, help_text='Название поля в Application или Student, откуда брать значение при отсутствии загруженного доказательства', max_length=50, null=True, verbose_name='Поле автозаполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Ключевое слово')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Область')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('answer_variant_a', models.TextField(default=None, verbose_name='Вариант a')),
                ('answer_variant_b', models.TextField(default=None, verbose_name='Вариант b')),
                ('answer_variant_c', models.TextField(default=None, verbose_name='Вариант c')),
                ('question_type', models.CharField(choices=[('psychological', 'Психологическая совместимость'), ('daily_routine', 'Режим дня'), ('habits', 'Вредные привычки'), ('values', 'Ценности'), ('household', 'Бытовые привычки')], max_length=50, verbose_name='Тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'permissions': [('can_manage_students', 'Can manage students')],
            },
            bases=('dorm.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('dorm.user',),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='waiting_for_admin', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_images/', verbose_name='Фото')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dorm.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_keywords', related_query_name='evidence_keyword', to='dorm.evidencetype')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_keywords', to='dorm.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/', verbose_name='Файл доказательства')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Числовое значение')),
                ('approved', models.BooleanField(blank=True, help_text='Если True – справка одобрена, если False – отклонена, если None – не проверена', null=True, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='dorm.application', verbose_name='Заявка')),
                ('evidence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.evidencetype', verbose_name='Тип доказательства')),
            ],
        ),
        migrations.AddField(
            model_name='evidencetype',
            name='keywords',
            field=models.ManyToManyField(blank=True, through='dorm.EvidenceKeyword', to='dorm.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dorm.chat')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInDorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Группа')),
                ('order', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Ордер')),
                ('room', models.CharField(blank=True, max_length=10, null=True, verbose_name='Комната')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Заявление', to='dorm.application', verbose_name='application')),
                ('dorm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Общежитие', to='dorm.dorm', verbose_name='dorm')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Студент', to='dorm.student', verbose_name='student')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='dorm.student', verbose_name='Студент'),
        ),
    ]
