# Generated by Django 5.1.1 on 2024-09-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_places', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('rooms_for_two', models.PositiveIntegerField(verbose_name='Количество комнат на 2')),
                ('rooms_for_three', models.PositiveIntegerField(verbose_name='Количество комнат на 3')),
                ('rooms_for_four', models.PositiveIntegerField(verbose_name='Количество комнат на 4')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_s', models.CharField(max_length=100, verbose_name='S-ка студента')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('origin', models.CharField(max_length=255, verbose_name='Откуда студент')),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False, verbose_name='Одобрение')),
                ('test_result', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Результат теста')),
                ('dormitory_choice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm', verbose_name='Выбор по цене')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='dorm.student', verbose_name='Студент')),
            ],
        ),
    ]
