# Generated by Django 5.1.1 on 2025-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_keywords', models.TextField(verbose_name='Ключевые слова/вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
    ]
