# Generated by Django 5.1.1 on 2024-09-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_region_student_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='origin',
        ),
    ]
