# Generated by Django 5.1.1 on 2025-04-29 09:55

import dorm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_application_edit', models.BooleanField(default=False, verbose_name='Студентам разрешено редактировать заявки')),
            ],
            options={
                'verbose_name': 'Глобальная настройка',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.RemoveField(
            model_name='admin',
            name='department',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gpa',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('SUPER', 'Главный администратор'), ('OP', 'Оператор'), ('REQ', 'Администратор по работе с заявками')], default='OP', max_length=10, verbose_name='Роль администратора'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон родителей'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='address',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dorm',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, through='dorm.EvidenceKeyword', to='dorm.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='studentindorm',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/no-avatar.png', upload_to=dorm.models.avatar_upload_path),
        ),
    ]
