# Generated by Django 5.1.1 on 2024-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_remove_student_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
    ]
