# Generated by Django 5.1.1 on 2024-10-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_remove_student_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('psychological', 'Психологическая совместимость'), ('daily_routine', 'Режим дня'), ('habits', 'Вредные привычки'), ('values', 'Ценности'), ('household', 'Бытовые привычки')], max_length=50, verbose_name='Тип вопроса')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='dormitory_choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dorm.dorm', verbose_name='Выбор общежития'),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dorm.testquestion', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='dorm.application', verbose_name='Заявка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.testquestion', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.testanswer', verbose_name='Выбранный ответ')),
            ],
        ),
    ]
