# Generated by Django 5.1.1 on 2025-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_globalsettings_remove_admin_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_from_bot',
            field=models.BooleanField(default=False),
        ),
    ]
