# Generated by Django 5.1.1 on 2025-05-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_message_is_from_bot'),
    ]

    operations = [
    ]
