# Generated by Django 5.1.1 on 2025-05-31 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_auto_20250531_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentindorm',
            options={'verbose_name': 'Назначение студента в комнату', 'verbose_name_plural': 'Назначения студентов'},
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='rooms_for_four',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='rooms_for_three',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='rooms_for_two',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_operator_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencetype',
            name='special_housing',
            field=models.BooleanField(default=False, verbose_name='Заселять на 1–2 этаж'),
        ),
        migrations.AddField(
            model_name='message',
            name='operator_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='iin',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='studentindorm',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dorm_assignment', to='dorm.application', verbose_name='Заявление'),
        ),
        migrations.AddField(
            model_name='studentindorm',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время расселения'),
        ),
        migrations.AddField(
            model_name='studentindorm',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_dorm_assignments', to='dorm.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentindorm',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 101, 101A, 202Б', max_length=10, verbose_name='Номер комнаты')),
                ('capacity', models.PositiveSmallIntegerField(help_text='2, 3 или 4', verbose_name='Вместимость')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dorm.dorm', verbose_name='Общежитие')),
            ],
            options={
                'ordering': ['dorm__name', 'number'],
                'unique_together': {('dorm', 'number')},
            },
        ),
        migrations.AlterField(
            model_name='studentindorm',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_occupants', to='dorm.room', verbose_name='Комната'),
        ),
        migrations.AlterUniqueTogether(
            name='studentindorm',
            unique_together={('application', 'room')},
        ),
        migrations.RemoveField(
            model_name='studentindorm',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='studentindorm',
            name='dorm_id',
        ),
        migrations.RemoveField(
            model_name='studentindorm',
            name='student_id',
        ),
        migrations.CreateModel(
            name='StudentInRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=10)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='dorm.application')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='dorm.room')),
            ],
            options={
                'unique_together': {('application', 'room')},
            },
        ),
    ]
